
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        heroTitle: "Find Your Future, Work From Anywhere",
        heroSubtitle: "Easily connect with the best opportunities in both Government and Private sectors.",
        searchJob: "Search Job Title, Skills or Company",
        searchLocation: "Search by state or area name",
        findJobs: "Find Jobs",
        trendingJobs: "Trending Jobs",
        popularCategories: "Popular Categories",
        stats: {
            vacancies: "Live Vacancies",
            companies: "Partner Companies",
            candidates: "Happy Candidates"
        },
        jobTypes: {
            govt: "Government",
            private: "Private"
        },
        jobsByCategory: "Jobs by Category",
        recruitmentMadeEasy: "Recruitment Made Easy In 2 Minutes",
        allCategories: "All Categories",
        jobsAvailable: "Jobs Available",
        processTitle: "How It Works",
        processSubtitle: "Your simple 3-step journey to a new career",
        processSteps: [
            { t: "Create Account", d: "Join as an employee or employer and set up your professional profile in minutes." },
            { t: "Find Opportunities", d: "Search through thousands of live jobs across various industries and districts." },
            { t: "Apply & Grow", d: "Submit your application directly and take the next big step in your professional life." }
        ],
        footerDesc: "Your trusted gateway to the best career opportunities. Matching talent with the right employers across India.",
        quickLinks: "Quick Links",
        contactUs: "Contact Us",
        login: "Login",
        register: "Register",
        allDistricts: "All Districts",
        browseTrending: "Browse Trending Jobs",
        dontMissOpenings: "Don't miss out on these current openings",
        viewAllOpportunities: "View All Opportunities",
        resultsFor: "Results for",
        opportunitiesFound: "Opportunities found",
        noResultFound: "No result found for",
        searchAdvice: "Try searching for another keyword or check for spelling errors in your search query.",
        searchNewJobs: "Search New Jobs",
        opportunities: "Opportunities",
        jobsForYou: "Recommended Jobs",
        lastDate: "Last Date",
        salary: "Salary",
        vacancy: "Vacancy",
        allIndia: "All India",
        govt: "Government",
        private: "Private",
        employee: "Employee",
        employer: "Employer",
        joinAsEmployee: "Join as Employee",
        joinAsEmployer: "Join as Employer",
        startJourney: "Start your journey today",
        startHiring: "Start Hiring Professionals",
        fullName: "Full Name",
        emailId: "Email Address",
        mobileNumber: "Mobile Number",
        companyName: "Company Name",
        contactPerson: "Contact Person Name",
        continueToVerify: "Continue to Verify",
        verificationCode: "Verification Code",
        verifyAccount: "Verify Code",
        differentNumber: "Edit Details",
        verified: "Verified",
        finalizeReg: "Complete Registration",
        alreadyAccount: "Already have an account?",
        loginHere: "Login here",
        memberLogin: "Member Login",
        forgotPassword: "Forgot Password",
        secureLogin: "Secure Login",
        needAccount: "Need an account?",
        registerSeeker: "Register Seeker",
        registerEmployer: "Register Employer",
        representCompany: "Represent a company?",
        regionalSearch: "Regional Search",
        findJobsByDistrict: "Find Jobs by District",
        viewAllDistricts: "View All Districts",
        categories: {
            administrative: "Administrative",
            it: "IT / Telecom",
            labour: "Labour & Helper",
            marketing: "Marketing",
            medical: "Medical",
            office: "Office Staff",
            sales: "Sales",
            technician: "Technician"
        },
        backToListings: "Back to listings",
        applyNow: "Apply Now",
        jobDescription: "Job Description",
        jobRequirements: "Job Requirements",
        experience: "Experience",
        jobTypeTag: "Job Type",
        languages: "Languages",
        aboutCompany: "About Company",
        importantDates: "Important Dates",
        jobStatus: "Job Status",
        posted: "Posted",
        expires: "Expires",
        status: "Status",
        active: "Active",
        modeOfApp: "Mode of Application",
        modeOfExam: "Mode of Examination",
        qualification: "Qualification",
        ageRelaxation: "Age Relaxation",
        rolesResp: "Roles & Responsibilities",
        requiredSkills: "Required Skills",
        confirmDetails: "Confirm Your Details",
        completeProfile: "Complete Your Profile",
        reviewInfo: "Review your info before applying",
        tellUsMore: "Tell us more about yourself to apply",
        education: "Education",
        location: "Location",
        uploadResume: "Upload Resume for this Job",
        chooseResume: "Choose a Resume File",
        confirmApply: "Confirm & Apply",
        editProfile: "Edit Profile",
        birthDate: "Birth Date",
        currentAddress: "Current Address",
        city: "City",
        district: "District",
        workExperience: "Work Experience",
        fresher: "Fresher",
        experienced: "Experienced",
        designation: "Current/Last Designation",
        resumeUploadReq: "Resume Upload (Required)",
        saveProfileApply: "Save Profile & Apply",
        selectExperience: "Select Experience",
        keywordRequired: "(please enter a keyword to search relevant jobs)",
        expYears: "years",
        expYear: "year",
        expFresher: "Fresher (less than 1 year)",
        home: "Home",
        about: "About",
        services: "Services",
        contact: "Contact",
        platform: "Platform",
        hireTalent: "Hire Talent",
        locations: "Tamil Nadu, India",
        allRightsReserved: "All Rights Reserved.",
        privacyPolicy: "Privacy Policy",
        termsOfService: "Terms of Service",
        candidateSuccess: "Candidate Success",
        voicesOfSuccess: "Voices of Success",
        reviewsSubtitle: "Discover what candidates have to say about their hiring journey through our platform.",
        candidate: "Candidate",
        reviewed: "Reviewed",
        at: "at",
        jobPortalTagline: "India's #1 Job Portal",
        verifiedStatus: "Verified Status",
        trustedCompany: "Trusted by 1000+ Companies",
        activeJobs: "Active Jobs",
        placements: "Placements",
        companies: "Companies",
        hiringMadeEasy: "Hiring Made Easy",
        registerDesc: "Join us and find your dream job with ease.",
        verifiedDesc: "Get your profile verified by our experts.",
        interview: "Interview",
        interviewDesc: "Attend interviews with top companies.",
        hiredDesc: "Apply to top companies and get hired fast.",
        hired: "Hired",
        readyToBegin: "Ready to Begin Your Journey?",
        ctaDesc: "Join thousands of successful candidates and find your dream career today.",
        joinAsSeeker: "Join as Seeker",
        joinAsCompany: "Join as Company",
        backToHome: "Back to Home",
        tamilNadu: "Tamil Nadu",
        districts: "Districts",
        districtsDiscovered: "Districts discovered",
        locateDistrict: "Locate your district...",
        exploreJobs: "Explore Jobs",
        noDistrictFound: "No District Found",
        noMatchingDistrict: "We couldn't find any district matching",
        careerProgress: "Career\nProgress",
        employeeAccount: "Employee Account",
        signOut: "Sign Out",
        employerHub: "Employer Hub",
        candidatePortal: "Candidate Portal",
        verifiedAccount: "Verified Account",
        overview: "Overview",
        myApplications: "My Applications",
        companyProfile: "Company Profile",
        postNewJob: "Post New Job",
        myJobs: "My Jobs",
        applicantReports: "Applicant Reports",
        manageReviews: "Manage Reviews",
        welcomeBack: "Welcome back",
        dashboardSummary: "Here's a summary of your career progress.",
        totalApplied: "Total Applied",
        shortlisted: "Shortlisted",
        pendingReview: "Pending/Under Review",
        recentActivity: "Recent Activity",
        underReview: "Under Review",
        viewAllApps: "View All Applications",
        noRecentApps: "No recent applications found.",
        employerDashboard: "Employer Dashboard",
        welcomeBackToday: "Welcome back! Here's what's happening today.",
        postNewVacancy: "Post New Vacancy",
        totalJobs: "Total Jobs",
        activeListings: "Active Listings",
        applications: "Applications",
        quickActions: "Quick Actions",
        manageJobs: "Manage Jobs",
        editCloseListings: "Edit or close active listings",
        viewCandidates: "View Candidates",
        reviewApplicantProfiles: "Review applicant profiles",
        updateProfilePrompt: "Need to update profile?",
        companyInfoUpdate: "Keep your company information up to date to attract better candidates.",
        goToProfile: "Go to Profile",
        districtsList: {
            "Ariyalur": "Ariyalur",
            "Chengalpattu": "Chengalpattu",
            "Chennai": "Chennai",
            "Coimbatore": "Coimbatore",
            "Cuddalore": "Cuddalore",
            "Dharmapuri": "Dharmapuri",
            "Dindigul": "Dindigul",
            "Erode": "Erode",
            "Kallakurichi": "Kallakurichi",
            "Kanchipuram": "Kanchipuram",
            "Kanyakumari": "Kanyakumari",
            "Karur": "Karur",
            "Krishnagiri": "Krishnagiri",
            "Madurai": "Madurai",
            "Mayiladuthurai": "Mayiladuthurai",
            "Nagapattinam": "Nagapattinam",
            "Namakkal": "Namakkal",
            "Nilgiris": "Nilgiris",
            "Perambalur": "Perambalur",
            "Pudukkottai": "Pudukkottai",
            "Ramanathapuram": "Ramanathapuram",
            "Ranipet": "Ranipet",
            "Salem": "Salem",
            "Sivaganga": "Sivaganga",
            "Tenkasi": "Tenkasi",
            "Thanjavur": "Thanjavur",
            "Theni": "Theni",
            "Thoothukudi": "Thoothukudi",
            "Tiruchirappalli": "Tiruchirappalli",
            "Tirunelveli": "Tirunelveli",
            "Tirupathur": "Tirupathur",
            "Tiruppur": "Tiruppur",
            "Tiruvallur": "Tiruvallur",
            "Tiruvannamalai": "Tiruvannamalai",
            "Tiruvarur": "Tiruvarur",
            "Vellore": "Vellore",
            "Viluppuram": "Viluppuram",
            "Virudhunagar": "Virudhunagar",
            "Trichy": "Trichy"
        },
        changeRegion: "Change Region",
        jobsIn: "Jobs",
        privateSector: "Private Sector",
        govtSector: "Govt Sector",
        availablePositions: "Positions Available",
        noJobsInDistrict: "No jobs found in this district",
        browseOtherDistricts: "Browse Other Districts",
        matchInOtherLocations: "Similar Jobs in Other Locations",
        similarJobs: "Jobs you might be interested in",
        getInTouch: "Get in Touch",
        contactSubtitle: "Recruitment Made Easy In 2 Minutes",
        directCall: "Direct Call",
        emailSupport: "Email Support",
        mainOffice: "Main Office",
        completeName: "Complete Name",
        howCanHelp: "How Can We Help?",
        messagePlaceholder: "Write your message here...",
        sendMessage: "Send Message",
        messageSent: "Message sent successfully!",
        sending: "Sending...",
        namePlaceholder: "Enter your full name",
        emailPlaceholder: "Enter your email address",
        contactInfo: "Contact Information",
        contactInfoDesc: "Have questions? We're here to help you every step of the way."
    },
    ta: {
        heroTitle: "உங்கள் எதிர்காலத்தை கண்டறியுங்கள், எங்கிருந்தும் பணிபுரியுங்கள்",
        heroSubtitle: "அரசு மற்றும் தனியார் துறைகளில் சிறந்த வாய்ப்புகளை எளிதாக இணைக்கவும்.",
        searchJob: "வேலை, நிறுவனங்களைத் தேடுங்கள்...",
        searchLocation: "மாநிலம் அல்லது பகுதி பெயர்...",
        findJobs: "வேலைகளைத் தேடுங்கள்",
        trendingJobs: "பிரபலமான வேலைகள்",
        popularCategories: "பிரபலமான பிரிவுகள்",
        stats: {
            vacancies: "நேரடி காலியிடங்கள்",
            companies: "கூட்டு நிறுவனங்கள்",
            candidates: "மகிழ்ச்சியான வேட்பாளர்கள்"
        },
        jobTypes: {
            govt: "அரசாங்கம்",
            private: "தனியார்"
        },
        jobsByCategory: "பிரிவு வாரியாக வேலைகள்",
        recruitmentMadeEasy: "2 நிமிடங்களில் ஆட்சேர்ப்பு எளிதாக்கப்பட்டது",
        allCategories: "அனைத்து பிரிவுகளும்",
        jobsAvailable: "வேலைகள் உள்ளன",
        processTitle: "இது எப்படி வேலை செய்கிறது",
        processSubtitle: "புதிய வாழ்க்கைக்கு உங்கள் எளிய 3-படி பயணம்",
        processSteps: [
            { t: "கணக்கை உருவாக்குங்கள்", d: "ஒரு பணியாளராக அல்லது முதலாளியாகச் சேர்ந்து உங்கள் தொழில்முறை சுயவிவரத்தை நிமிடங்களில் அமைக்கவும்." },
            { t: "வாய்ப்புகளைக் கண்டறியுங்கள்", d: "பல்வேறு துறைகள் மற்றும் மாவட்டங்களில் ஆயிரக்கணக்கான நேரடி வேலைகளைத் தேடுங்கள்." },
            { t: "விண்ணப்பித்து வளருங்கள்", d: "உங்கள் விண்ணப்பத்தை நேரடியாக சமர்ப்பித்து உங்கள் தொழில் வாழ்க்கையில் அடுத்த பெரிய படியை எடுங்கள்." }
        ],
        footerDesc: "சிறந்த தொழில் வாய்ப்புகளுக்கான உங்கள் நம்பகமான நுழைவாயில். இந்தியா முழுவதிலும் உள்ள சரியான முதலாளிகளுடன் திறமையாளர்களை இணைத்தல்.",
        quickLinks: "விரைவான இணைப்புகள்",
        contactUs: "எங்களைத் தொடர்பு கொள்ளுங்கள்",
        login: "உள்நுழை",
        register: "பதிவு செய்க",
        allDistricts: "அனைத்து மாவட்டங்களும்",
        browseTrending: "பிரபலமான வேலைகளை உலாவுக",
        dontMissOpenings: "தற்போதைய காலியிடங்களைத் தவறவிடாதீர்கள்",
        viewAllOpportunities: "அனைத்து வாய்ப்புகளையும் காண்க",
        matchInOtherLocations: "மற்ற இடங்களில் உள்ள ஒத்த வேலைகள்",
        similarJobs: "நீங்கள் விரும்பக்கூடிய ஒத்த வேலைகள்",
        resultsFor: "முடிவுகள்",
        opportunitiesFound: "வாய்ப்புகள் கண்டறியப்பட்டன",
        noResultFound: "முடிவுகள் எதுவும் இல்லை",
        searchAdvice: "மற்றொரு முக்கிய சொல்லைத் தேட முயற்சிக்கவும் அல்லது உங்கள் தேடல் வினவலில் எழுத்துப் பிழைகள் உள்ளதா எனச் சரிபார்க்கவும்.",
        searchNewJobs: "புதிய வேலைகளைத் தேடுங்கள்",
        opportunities: "வாய்ப்புகள்",
        jobsForYou: "பரிந்துரைக்கப்பட்ட வேலைகள்",
        lastDate: "கடைசி தேதி",
        salary: "சம்பளம்",
        vacancy: "காலியிடம்",
        allIndia: "இந்தியா முழுவதும்",
        govt: "அரசாங்கம்",
        private: "தனியார்",
        employee: "பணியாளர்",
        employer: "முதலாளி",
        joinAsEmployee: "பணியாளராக சேரவும்",
        joinAsEmployer: "முதலாளியாக சேரவும்",
        startJourney: "இன்று உங்கள் பயணத்தைத் தொடங்குங்கள்",
        startHiring: "தொழில்முறை வல்லுநர்களை வேலைக்கு அமர்த்தத் தொடங்குங்கள்",
        fullName: "முழு பெயர்",
        emailId: "மின்னஞ்சல் முகவரி",
        mobileNumber: "கைபேசி எண்",
        companyName: "நிறுவனத்தின் பெயர்",
        contactPerson: "தொடர்பு நபர் பெயர்",
        continueToVerify: "சரிபார்க்க தொடரவும்",
        verificationCode: "சரிபார்ப்பு குறியீடு",
        verifyAccount: "குறியீட்டைச் சரிபார்க்கவும்",
        differentNumber: "விவரங்களைத் திருத்தவும்",
        verified: "சரிபார்க்கப்பட்டது",
        finalizeReg: "பதிவை முடிக்கவும்",
        alreadyAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
        loginHere: "இங்கே உள்நுழையவும்",
        memberLogin: "உறுப்பினர் உள்நுழைவு",
        forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா",
        secureLogin: "பாதுகாப்பான உள்நுழைவு",
        needAccount: "கணக்கு தேவைப்படுகிறதா?",
        registerSeeker: "வேலை தேடுபவர் பதிவு",
        registerEmployer: "முதலாளி பதிவு",
        representCompany: "ஒரு நிறுவனத்தைப் பிரதிநிதித்துவப்படுத்துகிறீர்களா?",
        regionalSearch: "மண்டல தேடல்",
        findJobsByDistrict: "மாவட்ட வாரியாக வேலைகளைத் தேடுங்கள்",
        viewAllDistricts: "அனைத்து மாவட்டங்களையும் காண்க",
        categories: {
            administrative: "நிர்வாகம்",
            it: "தகவல் தொழில்நுட்பம்",
            labour: "தொழிலாளர் மற்றும் உதவியாளர்",
            marketing: "சந்தைப்படுத்தல்",
            medical: "மருத்துவம்",
            office: "அலுவலக ஊழியர்கள்",
            sales: "விற்பனை",
            technician: "தொழில்நுட்ப வல்லுநர்"
        },
        backToListings: "பட்டியலுக்குத் திரும்பு",
        applyNow: "இப்போது விண்ணப்பிக்கவும்",
        jobDescription: "வேலை விவரம்",
        jobRequirements: "வேலை தேவைகள்",
        experience: "அனுபவம்",
        jobTypeTag: "வேலை வகை",
        languages: "மொழிகள்",
        aboutCompany: "நிறுவனத்தைப் பற்றி",
        importantDates: "முக்கிய தேதிகள்",
        jobStatus: "வேலை நிலை",
        posted: "பதிவிடப்பட்டது",
        expires: "காலாவதியாகிறது",
        status: "நிலை",
        active: "செயலில் உள்ளது",
        modeOfApp: "விண்ணப்ப முறை",
        modeOfExam: "தேர்வு முறை",
        qualification: "தகுதி",
        ageRelaxation: "வயது தளர்வு",
        rolesResp: "பாத்திரங்கள் மற்றும் பொறுப்புகள்",
        requiredSkills: "தேவையான திறன்கள்",
        confirmDetails: "உங்கள் விவரங்களை உறுதிப்படுத்தவும்",
        completeProfile: "உங்கள் சுயவிவரத்தை முடிக்கவும்",
        reviewInfo: "விண்ணப்பிக்கும் முன் உங்கள் தகவலை மதிப்பாய்வு செய்யவும்",
        tellUsMore: "விண்ணப்பிக்க உங்களைப் பற்றி மேலும் எங்களிடம் கூறுங்கள்",
        education: "கல்வி",
        location: "இடம்",
        uploadResume: "இந்த வேலைக்கான விண்ணப்பத்தை பதிவேற்றவும்",
        chooseResume: "விண்ணப்ப கோப்பைத் தேர்ந்தெடுக்கவும்",
        confirmApply: "உறுதிப்படுத்தி விண்ணப்பிக்கவும்",
        editProfile: "சுயவிவரத்தைத் திருத்து",
        birthDate: "பிறந்த தேதி",
        currentAddress: "தற்போதைய முகவரி",
        city: "நகரம்",
        district: "மாவட்டம்",
        workExperience: "பணி அனுபவம்",
        fresher: "புதியவர்",
        experienced: "அனுபவம் வாய்ந்தவர்",
        designation: "தற்போதைய/கடந்த பதவி",
        resumeUploadReq: "விண்ணப்பம் பதிவேற்றம் (தேவை)",
        saveProfileApply: "சுயவிவரத்தைச் சேமித்து விண்ணப்பிக்கவும்",
        selectExperience: "அனுபவத்தைத் தேர்ந்தெடுக்கவும்",
        keywordRequired: "(பொருத்தமான வேலைகளைத் தேட ஒரு முக்கிய சொல்லை உள்ளிடவும்)",
        expYears: "ஆண்டுகள்",
        expYear: "ஆண்டு",
        expFresher: "புதியவர் (1 வருடத்திற்கும் குறைவானது)",
        home: "முகப்பு",
        about: "எங்களைப் பற்றி",
        services: "சேவைகள்",
        contact: "தொடர்பு",
        platform: "தளம்",
        hireTalent: "திறமையாளர்களை வேலைக்கு அமர்த்தவும்",
        locations: "தமிழ்நாடு, இந்தியா",
        allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
        privacyPolicy: "தனியுரிமைக் கொள்கை",
        termsOfService: "சேவை விதிமுறைகள்",
        candidateSuccess: "வேட்பாளர் வெற்றி",
        voicesOfSuccess: "வெற்றியின் குரல்கள்",
        reviewsSubtitle: "எங்கள் தளம் மூலம் வேட்பாளர்கள் தங்களது பணியமர்த்தல் பயணத்தைப் பற்றி என்ன கூறுகிறார்கள் என்பதைக் கண்டறியுங்கள்.",
        candidate: "Candidate",
        reviewed: "மதிப்பாய்வு செய்யப்பட்டது",
        at: "இல்",
        jobPortalTagline: "இந்தியாவின் #1 வேலைவாய்ப்பு தளம்",
        verifiedStatus: "சரிபார்க்கப்பட்ட நிலை",
        trustedCompany: "1000+ நிறுவனங்களால் நம்பப்படுகிறது",
        activeJobs: "செயலில் உள்ள வேலைகள்",
        placements: "பணி நியமனங்கள்",
        companies: "நிறுவனங்கள்",
        hiringMadeEasy: "ஆட்சேர்ப்பு எளிதாக்கப்பட்டது",
        registerDesc: "எந்தவொரு சிரமமும் இன்றி உங்கள் கனவுப் பணியைக் கண்டறிய இணைந்திடுங்கள்.",
        verifiedDesc: "உங்கள் சுயவிவரத்தை எங்கள் நிபுணர்களால் சரிபார்க்கவும்.",
        interview: "நேர்காணல்",
        interviewDesc: "முன்னணி நிறுவனங்களுடன் நேர்காணல்களில் கலந்து கொள்ளுங்கள்.",
        hiredDesc: "சிறந்த நிறுவனங்களுக்கு விண்ணப்பித்து விரைவாக வேலை பெறுங்கள்.",
        hired: "வேலை கிடைத்தது",
        readyToBegin: "உங்கள் பயணத்தைத் தொடங்க தயாரா?",
        ctaDesc: "ஆயிரக்கணக்கான வெற்றிகரமான வேட்பாளர்களுடன் இணைந்து இன்று உங்கள் கனவு வாழ்க்கையைக் கண்டறியுங்கள்.",
        joinAsSeeker: "வேலை தேடுபவராக சேருங்கள்",
        joinAsCompany: "நிறுவனமாக சேருங்கள்",
        backToHome: "முகப்பிற்குத் திரும்பு",
        tamilNadu: "தமிழ்நாடு",
        districts: "மாவட்டங்கள்",
        districtsDiscovered: "மாவட்டங்கள் கண்டறியப்பட்டன",
        locateDistrict: "உங்கள் மாவட்டத்தைக் கண்டறியவும்...",
        exploreJobs: "வேலைகளை ஆராயுங்கள்",
        noDistrictFound: "மாவட்டம் எதுவும் இல்லை",
        noMatchingDistrict: "உடன் பொருந்தக்கூடிய எந்த மாவட்டத்தையும் எங்களால் கண்டுபிடிக்க முடியவில்லை",
        careerProgress: "தொழில்\nமுன்னேற்றம்",
        employeeAccount: "பணியாளர் கணக்கு",
        signOut: "வெளியேறு",
        employerHub: "முதலாளி மையம்",
        candidatePortal: "வேட்பாளர் தளம்",
        verifiedAccount: "சரிபார்க்கப்பட்ட கணக்கு",
        overview: "கண்ணோட்டம்",
        myApplications: "எனது விண்ணப்பங்கள்",
        companyProfile: "நிறுவனத்தின் விவரம்",
        postNewJob: "புதிய வேலை பதிவு",
        myJobs: "எனது வேலைகள்",
        applicantReports: "விண்ணப்பதாரர் அறிக்கைகள்",
        manageReviews: "மதிப்பாய்வுகளை நிர்வகிக்கவும்",
        welcomeBack: "மீண்டும் வருக",
        dashboardSummary: "உங்கள் தொழில் முன்னேற்றத்தின் சுருக்கம் இங்கே.",
        totalApplied: "மொத்தம் விண்ணப்பிக்கப்பட்டது",
        shortlisted: "தேர்வு செய்யப்பட்டது",
        pendingReview: "நிலுவையில் உள்ளது",
        recentActivity: "சமீபத்திய செயல்பாடு",
        underReview: "பரிசீலனையில் உள்ளது",
        viewAllApps: "அனைத்து விண்ணப்பங்களையும் காண்க",
        noRecentApps: "சமீபத்திய விண்ணப்பங்கள் எதுவும் இல்லை.",
        employerDashboard: "முதலாளி டேஷ்போர்டு",
        welcomeBackToday: "மீண்டும் வருக! இன்று என்ன நடக்கிறது என்பது இங்கே.",
        postNewVacancy: "புதிய காலியிடத்தை பதிவு செய்க",
        totalJobs: "மொத்த வேலைகள்",
        activeListings: "செயலில் உள்ள பட்டியல்கள்",
        applications: "விண்ணப்பங்கள்",
        quickActions: "விரைவான செயல்கள்",
        manageJobs: "வேலைகளை நிர்வகிக்கவும்",
        editCloseListings: "செயலில் உள்ள பட்டியல்களைத் திருத்தவும் அல்லது மூடவும்",
        viewCandidates: "வேட்பாளர்களைப் பார்க்கவும்",
        reviewApplicantProfiles: "விண்ணப்பதாரர் விவரங்களை மதிப்பாய்வு செய்யவும்",
        updateProfilePrompt: "சுயவிவரத்தைப் புதுப்பிக்க வேண்டுமா?",
        companyInfoUpdate: "சிறந்த வேட்பாளர்களை ஈர்க்க உங்கள் நிறுவனத்தின் தகவலைப் புதுப்பித்த நிலையில் வைத்திருங்கள்.",
        goToProfile: "சுயவிவரத்திற்குச் செல்லவும்",
        districtsList: {
            "Ariyalur": "அரியலூர்",
            "Chengalpattu": "செங்கல்பட்டு",
            "Chennai": "சென்னை",
            "Coimbatore": "கோயம்புத்தூர்",
            "Cuddalore": "கடலூர்",
            "Dharmapuri": "தர்மபுரி",
            "Dindigul": "திண்டுக்கல்",
            "Erode": "ஈரோடு",
            "Kallakurichi": "கள்ளக்குறிச்சி",
            "Kanchipuram": "காஞ்சிபுரம்",
            "Kanyakumari": "கன்னியாகுமரி",
            "Karur": "கரூர்",
            "Krishnagiri": "கிருஷ்ணகிரி",
            "Madurai": "மதுரை",
            "Mayiladuthurai": "மயிலாடுதுறை",
            "Nagapattinam": "நாகப்பட்டினம்",
            "Namakkal": "நாமக்கல்",
            "Nilgiris": "நீலகிரி",
            "Perambalur": "பெரம்பலூர்",
            "Pudukkottai": "புதுக்கோட்டை",
            "Ramanathapuram": "இராமநாதபுரம்",
            "Ranipet": "இராணிப்பேட்டை",
            "Salem": "சேலம்",
            "Sivaganga": "சிவகங்கை",
            "Tenkasi": "தென்காசி",
            "Thanjavur": "தஞ்சாவூர்",
            "Theni": "தேனி",
            "Thoothukudi": "தூத்துக்குடி",
            "Tiruchirappalli": "திருச்சிராப்பள்ளி",
            "Tirunelveli": "திருநெல்வேலி",
            "Tirupathur": "திருப்பத்தூர்",
            "Tiruppur": "திருப்பூர்",
            "Tiruvallur": "திருவள்ளூர்",
            "Tiruvannamalai": "திருவண்ணாமலை",
            "Tiruvarur": "திருவாரூர்",
            "Vellore": "வேலூர்",
            "Viluppuram": "விழுப்புரம்",
            "Virudhunagar": "விருதுநகர்",
            "Trichy": "திருச்சி"
        },
        changeRegion: "மண்டலத்தை மாற்றவும்",
        jobsIn: "வேலைகள்",
        privateSector: "தனியார் துறை",
        govtSector: "அரசுத் துறை",
        availablePositions: "காலியிடங்கள் உள்ளன",
        noJobsInDistrict: "இந்த மாவட்டத்தில் வேலைகள் எதுவும் இல்லை",
        browseOtherDistricts: "மற்ற மாவட்டங்களை உலாவுக",
        getInTouch: "தொடர்பு கொள்ளவும்",
        contactSubtitle: "2 நிமிடங்களில் எளிதான ஆட்சேர்ப்பு",
        directCall: "நேரடி அழைப்பு",
        emailSupport: "மின்னஞ்சல் ஆதரவு",
        mainOffice: "முதன்மை அலுவலகம்",
        completeName: "முழு பெயர்",
        howCanHelp: "நாங்கள் உங்களுக்கு எவ்வாறு உதவ முடியும்?",
        messagePlaceholder: "உங்கள் செய்தியை இங்கே பதிவிடவும்...",
        sendMessage: "செய்தியை அனுப்பவும்",
        messageSent: "செய்தி வெற்றிகரமாக அனுப்பப்பட்டது!",
        sending: "அனுப்பப்படுகிறது...",
        namePlaceholder: "உங்கள் முழுப் பெயரை உள்ளிடவும்",
        emailPlaceholder: "உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்",
        contactInfo: "தொடர்பு விவரங்கள்",
        contactInfoDesc: "கேள்விகள் உள்ளதா? உங்களுக்கு உதவ நாங்கள் இங்கு இருக்கிறோம்."
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'ta' : 'en');
    };

    const t = (key) => {
        const keys = key.split('.');
        let value = translations[language];
        for (const k of keys) {
            if (value && value[k]) {
                value = value[k];
            } else {
                let englishValue = translations['en'];
                let foundEn = true;
                for (const ek of keys) {
                    if (englishValue && englishValue[ek]) {
                        englishValue = englishValue[ek];
                    } else {
                        foundEn = false;
                        break;
                    }
                }
                return foundEn ? englishValue : key;
            }
        }
        return value;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
